### ISSUE TITLE
Handle TimeoutError

### ISSUE THREAD

**Issue by toadkicker** [vkobel/ethdrain#3]
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/ubuntu/ethdrain/ethdrain.py", line 109, in setup_process
    loop.run_until_complete(future)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/home/ubuntu/ethdrain/ethdrain.py", line 66, in run
    await asyncio.gather(*tasks)
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/home/ubuntu/ethdrain/ethdrain.py", line 50, in sema_fetch
    await fetch(url, session, block, process_fn, actions)
  File "/home/ubuntu/ethdrain/ethdrain.py", line 42, in fetch
    async with session.post(url, data=make_request(block), headers=HTTP_HEADERS) as response:
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 626, in __aenter__
    self._resp = yield from self._coro
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 295, in _request
    break
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/helpers.py", line 699, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/ethdrain/ethdrain.py", line 142, in <module>
    POOL.map(setup_process, CHUNKS)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
concurrent.futures._base.TimeoutError
```

**Comment by vkobel** [comment]
Fixed with 91088f953843c491ab3077f6119fd2ca4b23c04e
But maybe it would need a better kind of handling?
